seed = "0"
n = "10"
t1 = "2"
d_min = "1"
d_max = "2"
d_max_iter = "1000"
t2 = "3"
c_min = "3"
c_max = "4"
c_max_iter = "1000"
xi = "0.2"
islocal = "false"
isCL = "false"
degreefile = "sample/deg.dat"
communitysizesfile = "sample/cs.dat"
communityfile = "sample/com.dat"
networkfile = "sample/edge.dat"
nout = "0"